#!/usr/bin/env python
#-*-coding:utf-8 -*-

PERM_DESCRIPTION = {
	"SEND_SMS": ["dangerous", "发送短信"],
    "SEND_SMS_NO_CONFIRMATION": ["signatureOrSystem", "发送短信"],
    "RECEIVE_SMS": ["dangerous", "接收短信"],
    "RECEIVE_MMS": ["dangerous", "接收彩信"],
    "READ_SMS" : [ "dangerous" , "读短信或彩信"],
    "WRITE_SMS" : [ "dangerous" , "编辑短信或彩信"],
    "RECEIVE_WAP_PUSH" : [ "dangerous" , "接收WAP"],
    "BROADCAST_SMS" : [ "signature" , "发送短信广播" ],
    "BROADCAST_WAP_PUSH" : [ "signature" , "发送WAP推送广播"],
    "READ_CONTACTS" : [ "dangerous" , "读通讯录" ],
    "WRITE_CONTACTS" : [ "dangerous" , "写通讯录"],
    "READ_CALL_LOG": [ "dangerous", "读通话记录" ],
    "WRITE_CALL_LOG": [ "dangerous", "写通话记录"],
    "READ_CALENDAR" : [ "dangerous" , "读日历事件" ],
    "WRITE_CALENDAR": [ "dangerous" , "写日历事件"],
    "READ_HISTORY_BOOKMARKS" : [ "dangerous" , "读浏览器历史记录和书签"],
    "WRITE_HISTORY_BOOKMARKS" : [ "dangerous" , "写浏览器历史记录和书签"],
    "ACCESS_FINE_LOCATION" : [ "dangerous" , "手机GPS定位" ],
    "ACCESS_COARSE_LOCATION" : [ "dangerous" , "手机网络定位"],
    "ACCESS_MOCK_LOCATION" : [ "dangerous" , "修改手机定位"],
    "INTERNET" : [ "dangerous" , "访问因特网"],
    "ACCESS_NETWORK_STATE" : [ "normal" , "查看网络状态" ],
    "ACCESS_WIFI_STATE" : [ "normal" , "查看Wi-Fi状态" ],
    "CHANGE_WIFI_STATE" : [ "dangerous" , "修改Wi-Fi状态" ],
    "CHANGE_NETWORK_STATE" : [ "normal" , "修改网络状态"],
	"NFC" : [ "dangerous" , "执行NFC通信" ],
	"BLUETOOTH" : [ "dangerous" , "使用蓝牙" ],
	"BLUETOOTH_ADMIN" : [ "dangerous" , "管理蓝牙"],
    "READ_EXTERNAL_STORAGE" : [ "normal", "读SD卡" ],
    "START_ANY_ACTIVITY": [ "signature", "启动其他界面" ],
	"FORCE_STOP_PACKAGES" : [ "signature" , "停止其他程序" ],
	"MOUNT_UNMOUNT_FILESYSTEMS" : [ "signatureOrSystem" , "挂载文件系统" ],
	"MOUNT_FORMAT_FILESYSTEMS" : [ "signatureOrSystem" , "格式化SD卡" ],
	"BATTERY_STATS" : [ "dangerous" , "修改电量"  ],
	"WRITE_SETTINGS" : [ "normal" , "修改系统设置"],
	"RECORD_AUDIO" : [ "dangerous" , "录音" ],
	"CAMERA" : [ "dangerous" , "拍照录像" ],
	"PROCESS_OUTGOING_CALLS" : [ "dangerous" , "拦截拨号" ],
	"READ_PHONE_STATE" : [ "dangerous" , "读设备信息" ],
    "CALL_PHONE" : [ "dangerous" , "打电话" ],
	"WRITE_EXTERNAL_STORAGE" : [ "dangerous" , "写SD卡"],
	"GET_TASKS" : [ "dangerous" , "获得正在运行程序"],
    "RESTART_PACKAGES" : [ "normal" , "杀后台进程"],
	"KILL_BACKGROUND_PROCESSES" : [ "normal" , "杀后台进程"],
	"RECEIVE_BOOT_COMPLETED" : [ "normal" , "开机自启动" , ],
	"INSTALL_PACKAGES" : [ "signatureOrSystem" , "安装应用程序" ],
	"DELETE_PACKAGES" : [ "signatureOrSystem" , "删除应用程序" ],
	"FACTORY_TEST" : [ "signature" , "恢复出厂设置" ],
	"MASTER_CLEAR" : [ "signatureOrSystem" , "重置系统" ],
	"CALL_PRIVILEGED" : [ "signatureOrSystem" , "直接拨打电话" ],
}


